#!/bin/sh
#...........................
# Sets up a remote bare git
# repository by ssh.

GIT_DOMAIN=user@example.org
#...........................
ssh $GIT_DOMAIN 'mkdir -p ~/git/'$1'.git && cd ~/git/'$1'.git && git --bare init'
mkdir $1
cd $1
git init
git remote add origin ssh://$GIT_DOMAIN/~/git/$1.git
touch .gitignore
git add .
git commit -m 'Created new repo'
git push origin master
#echo '
#[branch "master"]
# remote = origin
#  merge = refs/heads/master' >>.git/config

echo "Your new git repo '$1' is ready and initialized at $GIT_DOMAIN/~/git/$1.git"
